#!/usr/bin/env bash
args=($@)

if [ -n "$DISCORD_TOKEN" ]; then
  args+=("-t $DISCORD_TOKEN")
fi

if [ -n "$GITHUB_TOKEN" ]; then
  args+=("--github-token $GITHUB_TOKEN")
fi

dotnet run -p TabletBot/TabletBot.csproj -- $(echo ${args[*]})
